cargo-features = ["edition2021"]

[package]
name = "sport_tech_overlay"
version = "0.5.1"
authors = ["Vladislav Nepogodin <nepogodin.vlad@gmail.com>"]
edition = "2018"

[profile.release]
lto = true
debug = 0
incremental = true
