name: macOS

on: [push]
env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: install_deps
      run: |
        curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | zsh
        brew install boost
      shell: zsh

    - name: Create Build Environment
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --parallel 10
