name: macOS

on:
  push:
    branches:
      - develop
  pull_request:

env:
  BUILD_TYPE: Debug

jobs:
  xcode:
    runs-on: macos-10.15
    strategy:
      matrix:
        xcode: [12.4, 12.3, 12.2, 12.1.1, 12.1, 12, 11.7, 11.6, 11.5, 11.4.1, 11.3.1, 11.2.1, 10.3]
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer

    steps:
      - uses: actions/checkout@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '6.2.0'
      - name: Configure CMake
        run: ./configure.sh
      - name: Build
        run: ./build.sh
