name: Release

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+*"]

env:
  BUILD_TYPE: Release
  GITHUB_TOKEN: ${{ secrets.SECRET_CI }}

jobs:
  windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '6.2.0'

      - name: Configure CMake
        run: cmake -S . -B build -G "Visual Studio 16 2019" -A x64 -DCMAKE_BUILD_TYPE=$BUILD_TYPE
      - name: Build CPP
        run: cmake --build build --config $BUILD_TYPE --parallel 10
      - name: Upload executable
        run: |
          cp ./build/Release/overlay.exe ./SportTech.exe
          ./.github/workflows/upload_asset.sh \
          ./SportTech.exe $GITHUB_TOKEN
