name: Ubuntu

on: [push]

env:
  BUILD_TYPE: Debug

jobs:
  gcc_build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install_deps
      run: |
        sudo apt update
        sudo apt install gcc-10 g++-10
        sudo apt install libboost-dev
      shell: bash

    - name: Create Build Environment
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE
      env:
        CC:   gcc-10
        CXX:  g++-10

    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --parallel 10

  clang_build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install_deps
      run: |
        sudo apt update
        sudo apt install clang-10
        sudo apt install libboost-dev
      shell: bash

    - name: Create Build Environment
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE
      env:
        CC:   clang-10
        CXX:  clang++-10

    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --parallel 10
