name: Windows

on: [push]

env:
  BUILD_TYPE: Debug

jobs:
  msvc2019:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -S . -B build -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=$BUILD_TYPE
    - name: Build
      run: cmake --build build --parallel 10

  clang10:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: install_clang
        run: curl -fsSL -o LLVM10.exe https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.0/LLVM-10.0.0-win64.exe ; 7z x LLVM10.exe -y -o"C:/Program Files/LLVM"

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_CXX_COMPILER="C:/Program Files/LLVM/bin/clang++.exe" -G"MinGW Makefiles" -DCMAKE_BUILD_TYPE=$BUILD_TYPE
      - name: Build
        run: cmake --build build --parallel 10

  clang-cl-10-x64:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure CMake
        run: cmake -S . -B build -G "Visual Studio 16 2019" -A x64 -T ClangCL -DCMAKE_BUILD_TYPE=$BUILD_TYPE
      - name: Build
        run: cmake --build build --parallel 10
